---
title: "r01_qual_filtering_exac_full_or"
output: html_document
editor_options: 
  chunk_output_type: console
---

Started: David Gilfoyle 2 May 2018  
Updated: David Gilfoyle 2 May 2018

---

# Summary

QUAL Filtering Based on TiTv Cut-off ~2.0  
Dataset: ExAC (full)  
Gene Selection: Olfactory Receptor Genes  
Input Variants: 69,726

# start_section

```{r start_section}

Sys.time()
rm(list=ls())
graphics.off()

# Make sure all the libraries installed 
#install.packages("vcfR")

# Install libraries
library(dplyr)
library(knitr)

# Setup input folder
input_folder="/home/ec2-user/results/r_import/exac_v1"

```

# load_rdata_file

```{r load_rdata_file}

# Load RData file - contains dataframe containing all variants
load(paste(input_folder, "r01_import_vcf_exac_full_or.RData", sep="/"))

# Check input dataframe
dim(fixed_exac_full_or.df)
class(fixed_exac_full_or.df)
str(fixed_exac_full_or.df)
colnames(fixed_exac_full_or.df)
fixed_exac_full_or.df[1:20,1:10]

# Setup base and output folders
base_folder="/home/ec2-user/scripts/qual_filt/exac_v1"
output_folder="/home/ec2-user/results/qual_filt/exac_v1"

getwd()
setwd(base_folder)
getwd()

opts_knit$set(root.dir = base_folder)

```

# qual_filtering

```{r qual_filtering}

# Filter QUAL > 997 based on source ExAC (Full Dataset) TiTv 1.98 (as determined by VCFStats)
fixed_qfilt_exac_full_or.df <- fixed_exac_full_or.df %>% 
  filter(QUAL > 997)

# Check output dataframe
dim(fixed_qfilt_exac_full_or.df)
class(fixed_qfilt_exac_full_or.df)
str(fixed_qfilt_exac_full_or.df)
colnames(fixed_qfilt_exac_full_or.df)
fixed_qfilt_exac_full_or.df[1:20,1:10]

# Cleanup
rm(fixed_exac_full_or.df)

```

# save_results

```{r save_results}

save.image(paste(output_folder, "r01_exac_full_or_qual_filt.RData", sep="/"))

```

# final_section

```{r final_section}

ls()
sessionInfo()
Sys.time()

```
